from __future__ import annotations

from app.models import AgentDefinition, AgentResult


def default_agent_factory(definition: AgentDefinition):
    """Return a deterministic local adapter; a real ADK adapter can replace this seam."""
    def execute(task: str) -> AgentResult:
        return AgentResult(
            agent_id=definition.id,
            status="completed",
            recommendation=f"{definition.name} recommends addressing: {task}",
            evidence=(f"Generated by configured {definition.id} v{definition.version}",),
        )
    return execute


class AgentAsTool:
    """Expose a resolved agent as a callable tool with a stable result contract."""

    def __init__(self, agent_id: str, execute):
        self.name = f"{agent_id}_tool"
        self.agent_id = agent_id
        self._execute = execute

    def __call__(self, task: str) -> AgentResult:
        if not task or not task.strip():
            raise ValueError("agent tool task must not be empty")
        return self._execute(task)
